set -g default-terminal "xterm-256color"
set -g terminal-features "xterm-256color:RGB"

set -g base-index 1
set -g renumber-windows on
set -g mouse on
set -g detach-on-destroy off
set -g pane-border-indicators arrows
set -g pane-border-lines heavy

set -g status-position top
set -g status-left-length "100"
set -g status-right ""
set -g status-style "fg=color240"
set -g window-status-current-style "fg=cyan"

unbind C-b
set -g prefix C-a

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

unbind v
unbind s
bind v split-window -h -c "#{pane_current_path}"
bind s split-window -v -c "#{pane_current_path}"

unbind p
bind p move-pane

bind r source-file "~/.config/tmux/tmux.conf"
bind a send-prefix
bind -r C-h previous-window
bind -r C-l next-window
bind -n C-f popup -E "~/.config/tmux/terminator.sh"
bind -n C-s popup -E "~/.config/tmux/sshifier.py"
bind X set-window-option synchronize-panes \; display-message "sync #{?pane_synchronized,on,off}"

set -g mode-keys vi
set -g copy-command 'wl-copy'

bind -T copy-mode-vi 'v'   send -X rectangle-off \; send -X begin-selection
bind -T copy-mode-vi 'C-v' send -X rectangle-on  \; send -X begin-selection
bind -T copy-mode-vi 'y'   send -X copy-selection-no-clear
bind -T copy-mode-vi MouseDragEnd1Pane send -X copy-selection
bind -T copy-mode-vi Escape {
    if-shell -F "#{selection_present}" { send -X clear-selection } { send -X cancel }
}
