-- stylua: ignore start
local c = {
    red          =  "#F17474",
    orange       =  "#EFA876",
    yellow       =  "#D5C15D",
    green        =  "#78BA78",
    cyan         =  "#6DA6AB",
    blue         =  "#7D8FE8",
    violet       =  "#A284CD",
    search       =  "#3A370D",
    visual       =  "#0D243A",
    bg_diff_add  =  "#152815",
    bg_diff_del  =  "#310C0C",
    bg1          =  "#1A1A1A",
    bg2          =  "#2e2e2e",
    bg3          =  "#454545",
    fg2          =  "#666666",
    fg1          =  "#d9d9d9",
}
-- stylua: ignore end

vim.cmd("hi clear")
vim.cmd("syntax reset")

local hl = function(name, val)
    vim.api.nvim_set_hl(0, name, val)
end

-- UI highlight
hl("Normal", { fg = c.fg1, bg = c.bg1 })
hl("NormalFloat", { fg = c.fg1 })
hl("FloatBorder", { fg = c.fg2 })
hl("ColorColumn", { bg = c.bg2 })
hl("Cursor", { fg = c.fg2, bg = c.fg1 })
hl("CursorLine", { bg = c.bg2 })
hl("CursorColumn", { bg = c.bg2 })
hl("Directory", { fg = c.fg1 })
hl("diffIndexLine", { fg = c.fg2 })
hl("diffLine", { fg = c.fg2 })
hl("diffFile", { fg = c.orange })
hl("diffOldFile", { fg = c.red })
hl("diffNewFile", { fg = c.green })
hl("DiffAdd", { bg = c.bg_diff_add })
hl("DiffAdded", { link = "DiffAdd" })
hl("DiffChange", { fg = c.orange })
hl("DiffDelete", { bg = c.bg_diff_del })
hl("DiffRemoved", { link = "DiffDelete" })
hl("DiffText", { fg = c.orange })
hl("EndOfBuffer", { bg = "NONE", fg = c.bg1 })
hl("ErrorMsg", { fg = c.red, underline = true })
hl("VertSplit", { fg = c.bg2 })
hl("WinSeparator", { fg = c.bg3 })
hl("Folded", { fg = c.fg2 })
hl("FoldColumn", { fg = c.fg2 })
hl("SignColumn", { fg = c.fg1 })
hl("Search", { fg = c.fg1, bg = c.search })
hl("IncSearch", { link = "Search" })
hl("CurSearch", { link = "Search" })
hl("LineNr", { fg = c.fg2 })
hl("CursorLineNr", { fg = c.yellow, bg = c.bg2 })
hl("MatchParen", { fg = c.fg1 })
hl("ModeMsg", { fg = c.fg1, bg = c.bg2 })
hl("MoreMsg", { fg = c.fg1, bg = c.bg2 })
hl("NonText", { fg = c.fg2 })
hl("Pmenu", { fg = c.fg1, bg = c.bg2 })
hl("PmenuSel", { fg = c.fg1, bg = c.fg2 })
hl("PmenuSbar", { bg = c.fg2 })
hl("PmenuThumb", { bg = c.fg2 })
hl("Question", { fg = c.blue })
hl("SpecialKey", { fg = c.fg1 })
-- for custom autocmd
hl("SingleWinStatusLine", { fg = c.fg1, bg = "NONE", italic = true })
hl("SingleWinStatusLineNC", { fg = c.fg2, bg = "NONE", italic = true })
hl("MultiWinStatusLine", { fg = c.fg1, bg = c.bg3, italic = true })
hl("MultiWinStatusLineNC", { fg = c.fg2, bg = c.bg2, italic = true })
-- default
hl("StatusLine", { link = "SingleWinStatusLine" })
hl("StatusLineNC", { link = "SingleWinStatusLineNC" })
--
hl("TabLine", { fg = c.fg2, bg = c.bg1 })
hl("TabLineFill", { fg = c.fg2, bg = c.bg1 })
hl("TablineSel", { fg = c.fg1, bg = c.bg3 })
hl("Title", { italic = true })
hl("Visual", { bg = c.visual })
hl("VisualNOS", { bg = c.visual })
hl("WarningMsg", { fg = c.yellow, bold = true })
hl("WildMenu", { fg = c.fg1, bg = c.blue })
hl("Comment", { fg = c.fg2, italic = true })
hl("Constant", { fg = c.violet })
hl("String", { fg = c.green })
hl("Character", { fg = c.cyan })
hl("Number", { fg = c.violet })
hl("Boolean", { fg = c.violet })
hl("Float", { fg = c.violet })
hl("Identifier", { fg = c.orange })
hl("Function", { fg = c.blue })
hl("Statement", { fg = c.violet })
hl("Conditional", { fg = c.orange, bold = true })
hl("Repeat", { fg = c.violet })
hl("Label", { fg = c.violet })
hl("Operator", { fg = c.fg1 })
hl("Keyword", { fg = c.orange, bold = true })
hl("Exception", { fg = c.orange })
hl("PreProc", { fg = c.violet })
hl("Include", { fg = c.orange, bold = true })
hl("Define", { fg = c.yellow, bold = true })
hl("Macro", { fg = c.yellow, bold = true })
hl("Type", { fg = c.cyan, bold = true })
hl("StorageClass", { fg = c.cyan, bold = true })
hl("Typedef", { fg = c.cyan, bold = true })
hl("Structure", { fg = c.yellow })
hl("Special", { fg = c.red })
hl("SpecialChar", { fg = c.red })
hl("Tag", { fg = c.cyan })
hl("Delimiter", { fg = c.fg1 })
hl("SpecialComment", { link = "Comment" })
hl("Debug", { fg = c.fg1 })
hl("Underlined", { underline = true })
hl("Ignore", { fg = c.fg1 })
hl("Error", { fg = c.red, underline = true })
hl("Todo", { fg = c.orange, bold = true })
hl("SpellBad", { fg = c.red, underline = true, sp = c.red })
hl("SpellCap", { fg = c.red, underline = true, sp = c.red })
hl("SpellRare", { fg = c.red, underline = true, sp = c.red })
hl("SpellLocale", { fg = c.red, underline = true, sp = c.red })
hl("Whitespace", { fg = c.fg2 })

--- Treesitter highlight
hl("@error", { fg = c.red })
hl("@text.literal", { fg = c.fg1 })
hl("@text.title", { fg = c.cyan, bold = true })
hl("@text.emphasis", { italic = true })
hl("@text.strong", { bold = true })
hl("@text.uri", { fg = c.blue, underline = true })
hl("@textReference", { fg = c.blue })
hl("@text.underline", { underline = true })
hl("@text.todo", { fg = c.orange, bold = true })
hl("@text.note", { fg = c.green, bold = true })
hl("@text.warning", { fg = c.yellow, bold = true })
hl("@text.danger", { fg = c.red, bold = true })
hl("@comment", { link = "Comment" })
hl("@punctuation", { fg = c.fg1 })
hl("@punctuation.special", { fg = c.cyan })
hl("@punctuation.bracket", { fg = c.fg1 })
hl("@punctuation.delimiter", { fg = c.fg1 })
hl("@constant", { fg = c.fg1 })
hl("@constant.macro", { fg = c.yellow, bold = true })
hl("@define", { fg = c.yellow, bold = true })
hl("@macro", { fg = c.yellow, bold = true })
hl("@string", { fg = c.green })
hl("@string.escape", { fg = c.blue })
hl("@stringEscape", { fg = c.blue })
hl("@string.special", { fg = c.blue })
hl("@string.regex", { fg = c.violet })
hl("@character", { fg = c.cyan })
hl("@character.special", { fg = c.blue })
hl("@number", { fg = c.violet })
hl("@boolan", { fg = c.violet, bold = true })
hl("@float", { fg = c.cyan })
hl("@function", { fg = c.cyan })
hl("@function.builtin", { link = "@function" })
hl("@function.macro", { fg = c.blue, bold = true })
hl("@attribute", { fg = c.orange })
hl("@annotation", { fg = c.yellow })
hl("@parameter", { fg = c.orange })
hl("@parameter.reference", { fg = c.orange })
hl("@method", { fg = c.blue })
hl("@field", { fg = c.cyan })
hl("@property", { fg = c.blue })
hl("@constructor", { fg = c.fg1 })
hl("@conditional", { fg = c.orange, bold = true })
hl("@repeat", { fg = c.orange, bold = true })
hl("@label", { fg = c.violet, italic = true })
hl("@operator", { fg = c.fg1 })
hl("@keyword", { fg = c.red })
hl("@keyword.function", { fg = c.red })
hl("@keyword.operator", { fg = c.orange })
hl("@exception", { fg = c.orange, bold = true })
hl("@variable", { fg = c.fg1 })
hl("@variable.builtin", { fg = c.violet })
hl("@variable.parameter", { fg = c.orange, italic = true })
hl("@type", { fg = c.yellow })
hl("@type.builtin", { link = "@type" })
hl("@type.qualifire", { fg = c.cyan })
hl("@type.definition", { fg = c.cyan, bold = true })
hl("@storageclass", { fg = c.orange, bold = true })
hl("@structure", { fg = c.cyan, bold = true })
hl("@namespace", { fg = c.orange })
hl("@include", { fg = c.orange, bold = true })
hl("@preproc", { fg = c.orange })
hl("@debug", { fg = c.yellow })
hl("@tag", { fg = c.cyan })
hl("@tag.delimiter", { fg = c.fg1 })
hl("@tag.attribute", { fg = c.orange })

-- python
hl("@constructor.python", { fg = c.yellow })
hl("@module.python", { fg = c.fg1 })
hl("@string.documentation.python", { link = "Comment" })
hl("@attribute.python", { fg = c.fg1 })

-- markdown
hl("@markup.heading.1.markdown", { fg = c.red, italic = true })
hl("@markup.heading.2.markdown", { fg = c.orange, italic = true })
hl("@markup.heading.3.markdown", { fg = c.yellow, italic = true })
hl("@markup.heading.4.markdown", { fg = c.green, italic = true })

-- json
hl("@property.json", { fg = c.blue, bold = true })

-- LSP semantic tokens
hl("@lsp.type.class", { link = "@type" })
hl("@lsp.type.decorator", { link = "@function" })
hl("@lsp.type.enum", { link = "@structure" })
hl("@lsp.type.enumMember", { link = "@property" })
hl("@lsp.type.function", { link = "@function" })
hl("@lsp.type.interface", { link = "@type" })
hl("@lsp.type.macro", { link = "@macro" })
hl("@lsp.type.method", { link = "@function" })
hl("@lsp.type.namespace", { link = "@namespace" })
hl("@lsp.type.parameter", { link = "@parameter" })
hl("@lsp.type.property", { link = "@property" })
hl("@lsp.type.struct", { link = "@structure" })
hl("@lsp.type.type", { link = "@type" })
hl("@lsp.type.typeParameter", { link = "@type" })
hl("@lsp.type.variable", { link = "@variable" })
hl("@lsp.type.keyword", { link = "@keyword" })

hl("htmlTag", { fg = c.cyan })
hl("htmlEndTag", { fg = c.cyan })
hl("htmlTagName", { fg = c.cyan })
hl("htmlSpecialTagName", { fg = c.cyan })
hl("htmlArg", { fg = c.orange })

-- hl("BufferLineIndicatorSelected", { bg = c.bg1 })
hl("BufferLineFill", { bg = c.bg2 })

hl("LspReferenceText", { bg = c.search })
hl("LspReferenceRead", { bg = c.blue })
hl("LspReferenceWrite", { bg = c.blue })

hl("DiagnosticUnderlineError", { underline = false, undercurl = false })
hl("DiagnosticUnderlineWarn", { underline = false, undercurl = false })
hl("DiagnosticUnderlineInfo", { underline = false, undercurl = false })
hl("DiagnosticUnderlineHint", { underline = false, undercurl = false })
hl("DiagnosticUnnecessary", { fg = c.fg2, italic = true })

hl("DiagnosticError", { fg = c.red, italic = true })
hl("DiagnosticWarn", { fg = c.yellow, italic = true })
hl("DiagnosticHint", { fg = c.blue, italic = true })
hl("DiagnosticInfo", { fg = c.cyan, italic = true })

hl("GitSignsAdd", { fg = c.green })
hl("GitSignsChange", { fg = c.yellow })
hl("GitSignsDelete", { fg = c.red })

-- indent-blankline
hl("Indent", { link = "VertSplit" })

-- FzfLua
hl("FzfLuaBorder", { link = "VertSplit" })
